import type { CommonContent } from '../types'
import { publishedCopy } from '@/lib/claims'

export const commonAr: CommonContent = {
  locale: 'ar',
  nav: [
    { key: 'home', label: 'الرئيسية' },
    { key: 'privateLabel', label: 'التصنيع بنظام Private Label' },
    { key: 'products', label: 'المنتجات' },
    { key: 'sampling', label: 'تطوير العينات' },
    { key: 'fabrics', label: 'الخامات والتشطيبات' },
    { key: 'howItWorks', label: 'خطوات العمل' },
    { key: 'international', label: 'التصنيع والتصدير الدولي' },
    { key: 'selectedWork', label: 'نماذج من الأعمال' },
    { key: 'guides', label: 'أدلة التصنيع' },
    { key: 'about', label: 'من نحن' },
    { key: 'faq', label: 'الأسئلة الشائعة' },
    { key: 'contact', label: 'تواصل معنا' },
  ],
  footerNav: [
    { key: 'home', label: 'الرئيسية' },
    { key: 'manufacturerEgypt', label: 'مصنع ملابس في مصر' },
    { key: 'privateLabel', label: 'التصنيع بنظام Private Label' },
    { key: 'lowMoq', label: 'تصنيع بحد أدنى منخفض' },
    { key: 'products', label: 'المنتجات' },
    { key: 'sampling', label: 'تطوير العينات' },
    { key: 'fabrics', label: 'الخامات والتشطيبات' },
    { key: 'howItWorks', label: 'خطوات العمل' },
    { key: 'international', label: 'التصنيع والتصدير الدولي' },
    { key: 'selectedWork', label: 'نماذج من الأعمال' },
    { key: 'startBrand', label: 'ابدأ براند ملابس' },
    { key: 'guides', label: 'أدلة التصنيع' },
    { key: 'about', label: 'من نحن' },
    { key: 'faq', label: 'الأسئلة الشائعة' },
    { key: 'contact', label: 'تواصل معنا' },
  ],
  brandTagline:
    'تصنيع ملابس بنظام Private Label وتطوير منتجات من مصر للبراندات في الشرق الأوسط وأوروبا وبريطانيا والولايات المتحدة وأسواق دولية أخرى.',
  skipToContent: 'الانتقال إلى المحتوى الرئيسي',
  languageSwitch: {
    label: 'اللغة',
    toEnglish: 'English',
    toArabic: 'العربية',
  },
  cta: {
    startProject: 'ناقش مشروعك معنا',
    requestSample: 'اطلب عينة',
    sendDesign: 'أرسل تصميمك أو الصور المرجعية',
    bookMeeting: 'احجز مكالمة',
    whatsapp: 'تواصل معنا عبر واتساب',
    contact: 'تواصل معنا',
    viewAll: 'عرض الكل',
    learnMore: 'اعرف المزيد',
  },
  workLabels: {
    project: 'نماذج مختارة من الأعمال',
    sample: 'تطوير العينات',
    concept: 'صورة تصورية — للاتجاه البصري فقط',
  },
  confidentialityNote: publishedCopy.confidentiality.ar,
  capabilityDisclaimer: publishedCopy.capabilityDisclaimer.ar,
  footer: {
    about:
      'تنسق Kemora تطوير وتصنيع الملابس بنظام Private Label في مصر من خلال مصانع شريكة حاصلة على الشهادات المناسبة، من أول عينة حتى التغليف ودعم التصدير.',
    navHeading: 'روابط الموقع',
    contactHeading: 'التواصل',
    emailLabel: 'البريد الإلكتروني',
    whatsappLabel: 'واتساب',
    rights: 'جميع الحقوق محفوظة.',
    privacy: 'سياسة الخصوصية',
    locations: 'مقرنا في مصر · نخدم أسواقًا دولية',
    status: 'نستقبل مشروعات جديدة حاليًا',
  },
  form: {
    heading: 'أخبرنا عن مشروعك',
    lead:
      'أرسل ما لديك: رسم أولي، صورة مرجعية، عينة جاهزة أو ملف تقني كامل. لا يشترط وجود ملف تقني (Tech Pack) للبدء.',
    name: 'الاسم',
    namePlaceholder: 'الاسم بالكامل',
    brand: 'اسم البراند',
    brandOptional: 'اختياري',
    email: 'البريد الإلكتروني',
    whatsapp: 'رقم الواتساب',
    whatsappHint: 'اختياري — البريد الإلكتروني يكفي إذا كنت تفضل ذلك. أضف كود الدولة إذا كتبت رقم واتساب.',
    country: 'الدولة',
    countryPlaceholder: 'مثال: السعودية، مصر، الإمارات',
    preferredLanguage: 'لغة التواصل المفضلة',
    languageOptions: [
      { value: 'arabic', label: 'العربية' },
      { value: 'english', label: 'الإنجليزية' },
    ],
    productCategory: 'فئة المنتج',
    productCategoryPlaceholder: 'اختر الفئة',
    quantity: 'الكمية التقديرية',
    quantityPlaceholder: 'مثال: 100 قطعة لكل موديل',
    hasDesigns: 'هل لديك تصميمات أو صور مرجعية؟',
    hasDesignsOptions: [
      { value: 'tech-pack', label: 'نعم — ملف تقني كامل' },
      { value: 'sketches', label: 'نعم — رسومات أو صور مرجعية' },
      { value: 'sample', label: 'نعم — عينة جاهزة لدي' },
      { value: 'none', label: 'ليس بعد — أحتاج مساعدة في تطوير المنتج' },
    ],
    message: 'الرسالة',
    messagePlaceholder:
      'اكتب لنا عن المنتج، الخامة، القَصّة أو الكمية التي تفكر فيها. لا مشكلة إذا كانت بعض التفاصيل غير محددة بعد.',
    messageOptional: 'اختيارية عند إرفاق ملفات',
    messageHint: 'أضف ملاحظة قصيرة، أو أرفق تصميمًا أو صورة مرجعية أو ملف PDF واحدًا على الأقل.',
    projectDetailsRequired:
      'يرجى إضافة رسالة قصيرة أو إرفاق تصميم أو صورة مرجعية أو ملف PDF واحد على الأقل.',
    consent:
      'أوافق على معالجة Kemora لبياناتي بغرض الرد على هذا الطلب فقط، وفقًا لما هو موضح في',
    consentLink: 'سياسة الخصوصية',
    submit: 'إرسال الطلب',
    sending: 'جارٍ الإرسال…',
    success: 'شكرًا لك — تم إرسال طلبك بنجاح.',
    successDetail: 'سنرد باستخدام بيانات التواصل التي أرسلتها.',
    error:
      'حدث خطأ ولم يتم إرسال الطلب. يرجى المحاولة مرة أخرى، أو مراسلتنا مباشرة على info@kemoratex.com.',
    attachmentTooLargeError:
      'الملفات المرفقة كبيرة جدًا لهذا النموذج. يرجى إرفاق حتى 5 ملفات بحجم إجمالي 3 ميجابايت، أو إرسال ملفات PDF الأكبر عبر البريد الإلكتروني أو واتساب بعد إرسال الطلب.',
    required: 'مطلوب',
    optional: 'اختياري',
    noTechPackNote:
      'لا يوجد لديك ملف تقني؟ هذا أمر طبيعي تمامًا في أول مجموعة — تكفي صورة أو رسم أولي للبدء.',
  },
  breadcrumbHome: 'الرئيسية',
}
